<html>

<h2>Catching Errors in a Flow</h2>
<p>How can we catch, and respond, to errors generated by a Flow?</p>
<p>We can always respond to possible exceptions by wrapping them in try/catch at the call site to avoid propagate errors throughout our Flow.</p>

<br>
<h3>üí° Helpful Resources</h3>
<ul>
    <li><a href="https://kotlinlang.org/docs/flow.html#exception-transparency">Exception Transparency Using Catch</a></li>
</ul>

<br>
<h3>üìù Instructions</h3>
<p>Use a try/catch to avoid throwing an exception when encountering a null value when building the flow</p>
<p>Alternatively, you could check for null and simply not emit a value.</p>

<br>
<h3>ü§î Observations</h3>
<ul>
    <li>Notice that once the exception is caught, the Flow terminates.</li>
    <li>How else might we handle the exception so that the flow might not terminate prematurely?</li>
</ul>
</html>